version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: simplelink-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: simplelink
      POSTGRES_PASSWORD: simplelink_dev_password
      POSTGRES_DB: simplelink
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U simplelink']
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: simplelink-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:8025']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    driver: local
